#! /bin/bash

# cowsay "This terminal is powered by 自由风"

LOGO="
       .__                  .__                .___
_______|  |__ _____    ____ |  |__ _____     __| _/
\___   /  |  \\__  \  /  _ \|  |  \\__  \   / __ | 
 /    /|   Y  \/ __ \(  <_> )   Y  \/ __ \_/ /_/ | 
/_____ \___|  (____  /\____/|___|  (____  /\____ | 
      \/    \/     \/            \/     \/      \/
"

LOGO_NAME="zhaohad_logo"
LOGO_PATH=`dirname $0`
LOGO_PATH="$LOGO_PATH/$LOGO_NAME"

cat $LOGO_PATH
echo -e "\n"

conda_env=`conda env list | grep "*" | sed '1q' | cut -d ' ' -f 1`

echo "Conda env: $conda_env"

echo -e "\n"

